### PR TITLE
AWS VPC support

### PR DESCRIPTION
**Pull request by adgaudio**
closes #298 

This PR revives work by @jtriley and @locojay to use StarCluster inside Amazon VPC and adds a couple bug fixes.  I have been using this successfully for about a week with no significant problems. 

Changes and details:
- When running in a vpc, the public "dns_name" is by default unavailable, which may make some StarCluster features fail when using the VPC.
- If using VPC, the clusters must be started (and ssh'd into) from inside the vpc.  We do not support ssh tunneling from outside the VPC (and we probably shouldn't) .
- If using VPC clusters with other nodes in the vpc, users may need to configure their security groups using this plugin: https://gist.github.com/adgaudio/5208195

UPDATE Oct. 6, 2013
- This PR is now fully backwards compatible with StarCluster (as of 8b3a01946bff4c3d70b955aba0ba61ad972c27b4)
  - If you were using an earlier version of this this PR, your clusters may not appear anymore.  see the commit msg 
- `starcluster terminate` will wait up to 5 minutes to terminate a security group in VPC.  Previously, it just failed to delete the security group because AWS is slow to remove dependencies from the security group.
- This PR includes GH #298 (ENH: Option to prefix dns name of clusters with the tag name. ie master on mycluster --> mycluster-master.)

### CODE REVIEW

**Comment by adgaudio** [comment]
this is ready to merge or for someone else to test out.  I'm using this successfully with no issues.

**Comment by adgaudio** [comment]
Thanks to @mjseid, this pr also supports creating spot instances in vpc.

**Comment by rqbanerjee** [comment]
Hi, I have some projects that need VPC support. What's the status of this pull request? Thanks adgaudio for submitting!

**Comment by adgaudio** [comment]
Hi Rajat,

I made some changes on Friday, but I believe you won't have problems to use
the current code. I'm also testing some more enhancements that I may
include tomorrow morning.

I updated the PR description.  Let me know if you have questions or
problems.

Alex

**Comment by adgaudio** [comment]
@jtriley, last we spoke about this branch, you mentioned that you would merge this into develop branch.  The pr is now fully backwards compatible, and I removed the last outstanding bug, where the security group didn't delete properly.

Can you please merge this or let me know what else I should do to get it merged?  As I continue to make pull requests to starcluster, this branch is increasingly more work for me to maintain.

**Comment by schmutze** [comment]
(copy to StarCluster@mit.edu as well)

Howdy,

AWS Solutions Architect here. I just wanted to confirm that we see a good amount of confusion from new users trying to use StarCluster in their accounts with VPC only support (default for all regions except us-east-1 for new AWS accounts).

If there are any outstanding issues on the AWS side preventing you from merging support for VPC into StarCluster, I'd be more than happy to help in any way that I can. Please don't hesitate to reach out to me.

Thanks for maintaining this extremely valuable research tool.

thanks,
chad

**Comment by jtriley** [comment]
@adgaudio Working on merging this now.

**Comment by adgaudio** [comment]
Fantastic!  That will be really great.  I have been getting a lot of
private emails asking about this branch as well.

Let me know if you need me to make any changes or run more tests.  I think
it is probably also worth our time to think about how we can better
document the vpc side of things.

Alex

**Comment by jtriley** [comment]
@adgaudio Docs is where I was heading next - can you do a brain dump of what's now possible with this PR and should be documented?

**Comment by jtriley** [comment]
@adgaudio Also, if you could jump into #starcluster on IRC (freenode) that'd be awesome. Some things are better discussed in real time.

**Comment by adgaudio** [comment]
Everything this pr does is documented in two places: the top of this pr, and also in #298.  On irc now :)

**Comment by adgaudio** [comment]
Awesome!  Thanks for pulling this in :)

**Comment by adgaudio** [comment]
@jtriley  - I'll add some documentation for the manual/configuration.rst page this weekend if you haven't already done so by then.

**Comment by jtriley** [comment]
@adgaudio That would be awesome. I'm currently working on putting out other fires (namely #304 and #312) so probably won't get to it until those are fixed.

**Pull request closed without merging**
