### PR TITLE
Various things 

### PR DESCRIPTION
**Pull request by yamins81**
Justin -- is there a chance you could merge some of my code into the master?   There are two fairly old PRs that would be great if had a chance to look at:

1) some additional options to addnode command. 

2) sge_utils.py module. 

3) Less important:  the new stuff in the loadbalancer code

Anyway, everything is merged with your most recent master head so it should be pretty easy.   Or let me know what would have to change?   There are some folks in my group who'd like to use this code, and I could get them to use my fork, but it might be better if they could just use the master. 

Thanks!
D

### CODE REVIEW

**Comment by jtriley** [comment]
@yamins81 Absolutely, sorry it has taken so long but this needed some serious code cleanup and review and I had already moved on in development well beyond a clean merge. Thanks for cleaning this up so that it's mergable in the develop branch. I'll start reviewing, testing, merging soon.

**Comment by jtriley** [comment]
@yamins81 Is it safe to delete the old pull request #20? 

Also, in the future it would be preferable to have pull requests in smaller chunks so that it's easier to review and merge. For example, this pull request more than likely could be split into a separate PR for addnode and another  for loadbalance. It's fine this time around but in the future this will help me to merge your stuff more quickly.

**Comment by yamins81** [comment]
On Fri, Jan 20, 2012 at 2:14 PM, Justin Riley <
reply@reply.github.com

> wrote:
> 
> @yamins81 Is it safe to delete the old pull request #20?
> 
> Also, in the future it would be preferable to have pull requests in
> smaller chunks so that it's easier to review and merge. For example, this
> pull request more than likely could be split into a separate PR for addnode
> and another  for loadbalance.

Yeah, I totally agree. I was actually going to write back to your earlier
email today seeing if you just wanted me to do that even now.  Merging the
addnode stuff would be a lot easier, and if you want, I can split up the
commits myself and resubmit.

D

**Comment by jtriley** [comment]
@yamins81 No problem, it's fine for now just wanted to make a note for future PR. I just got back from vacation so I'll start taking a look at this stuff this week and try to merge. Also, Is it safe to close your old pull request #20?

**Comment by yamins81** [comment]
closing this one!

**Pull request closed without merging**
