### PR TITLE
New plugin to install python packages with pip

### PR DESCRIPTION
**Pull request by ogrisel**
If you think this plugin is worth merging I will write a new section for the documentation.

### CODE REVIEW

**Comment by twiecki** [comment]
This is a great idea -- would love to see this make it in!

**Comment by ogrisel** [comment]
BTW: is there a way to run a oneliner bash command or a script on all the nodes of the cluster using something `starcluster something mycluster cmd`? For instance:

```
starcluster execcmd mycluster "pip install mylib"
starcluster execcmd mycluster "rm -rf /home/user/temp_folder"
```

**Comment by quasiben** [comment]
Kind of:

$ starcluster sshmaster mycluster 'cat /etc/hosts'
StarCluster - (http://web.mit.edu/starcluster)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

10.10.10.1 master
10.10.10.2 node001
10.10.10.3 node002

http://star.mit.edu/cluster/docs/0.93.3/manual/runcommands.html

**Comment by ogrisel** [comment]
Yes but then you have to pipe that with a cut and a second ssh command to send the actual command...

**Comment by ogrisel** [comment]
Or maybe use http://code.google.com/p/parallel-ssh/ from sshmaster instead.

**Comment by twiecki** [comment]
FYI: I gave this PR a test and it worked perfectly for me.

**Comment by jtriley** [comment]
@ogrisel This looks great! If you can add docs I'd be happy to merge it.

**Comment by ogrisel** [comment]
Alright, I am on it.

**Comment by ogrisel** [comment]
I pushed some documentation, ready for review.

**Comment by ogrisel** [comment]
I just rebased  on `develop` and raise `NotImplementedError` in `on_remove_node` callback

**Comment by ogrisel** [comment]
@jtriley Do you like the current plugin name? Would prefer if I renamed it to `PipInstaller` or `PyPkgInstaller` instead?

**Comment by jtriley** [comment]
@ogrisel I like `PyPkgInstaller` given that it's more generic than `PipInstaller`. Would you be up for refactoring the plugin and docs to do the rename?

**Comment by ogrisel** [comment]
I will try to do that tonight CET.

**Comment by ogrisel** [comment]
Done.

**Comment by jtriley** [comment]
@ogrisel Great work, thanks again!!!

**Comment by ogrisel** [comment]
Thanks!

**Pull request closed without merging**
