### PR TITLE
FIX: crash in shell command when ipcluster_dir already exists

### PR DESCRIPTION
**Pull request by ogrisel**

### CODE REVIEW

**Comment by ogrisel** [comment]
BTW, is there an easy way to add a non-regression test for this command?

**Comment by ogrisel** [comment]
Thanks @jtriley. BTW I will soon have a much simpler version of the IPCluster plugin that does not require the SGE queue. It shares some code with the existing plugin but is quite different as well. Any suggestion for the name of the plugin?

**Comment by jtriley** [comment]
@ogrisel I've been wanting to change the ipcluster plugin to not use SGE at all by default given that the current implementation takes up the entire SGE queue to run IPython parallel. Feel free to submit a pull request for this.

**Comment by ogrisel** [comment]
Alright! Do you want to maintain ipython 0.10 compat or shall I drop it as well?

**Comment by ogrisel** [comment]
I decided to drop the ipython 0.10 compat in #204 to simplify the code and future maintenance of the plugin.

**Pull request merged**
