### PR TITLE
FIX: security group has a name attribute

### PR DESCRIPTION
**Pull request by ogrisel**
At least it the case on my box with boto==2.5.2

### CODE REVIEW

**Comment by jtriley** [comment]
@ogrisel IIRC the launch.group-id filter for spot requests requires the actual auto-generated security group _id_ not the name. This was a subtle change in the EC2 API a while back that took a while to figure out (see https://github.com/boto/boto/issues/301#issuecomment-1824108).

Anyway, I just launched a spot cluster moments ago and the existing code still properly fetches the cluster's spot requests using the cluster group id so I'm not sure this is really needed. What's the problem you're having that this PR addresses?

**Comment by ogrisel** [comment]
In master I get the following `AttributeError`:

```
~> starcluster start -b 0.10 mycluster
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Using default cluster template: smallcluster
*** WARNING - ************************************************************
*** WARNING - SPOT INSTANCES ARE NOT GUARANTEED TO COME UP
*** WARNING - 
*** WARNING - Spot instances can take a long time to come up and may not
*** WARNING - come up at all depending on the current AWS load and your
*** WARNING - max spot bid price.
*** WARNING - 
*** WARNING - StarCluster will wait indefinitely until all instances (2)
*** WARNING - come up. If this takes too long, you can cancel the start
*** WARNING - command using CTRL-C. You can then resume the start command
*** WARNING - later on using the --no-create (-x) option:
*** WARNING - 
*** WARNING -     $ starcluster start -x mycluster
*** WARNING - 
*** WARNING - This will use the existing spot instances launched
*** WARNING - previously and continue starting the cluster. If you don't
*** WARNING - wish to wait on the cluster any longer after pressing CTRL-C
*** WARNING - simply terminate the cluster using the 'terminate' command.
*** WARNING - ************************************************************

*** WARNING - Waiting 5 seconds before continuing...
*** WARNING - Press CTRL-C to cancel...
5...4...3...2...1...
>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 2-node cluster...
>>> Launching master node (ami: ami-899d49e0, type: m1.small)...
>>> Creating security group @sc-mycluster...
Reservation:r-8d0c42ea
>>> Launching node001 (ami: ami-899d49e0, type: m1.small)
SpotInstanceRequest:sir-806f3612
>>> Waiting for cluster to come up... (updating every 30s)
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
Traceback (most recent call last):
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cli.py", line 255, in main
    sc.execute(args)
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/commands/start.py", line 194, in execute
    validate_running=validate_running)
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 1414, in start
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/utils.py", line 87, in wrap_f
    res = func(*arg, **kargs)
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 1437, in _start
    self.setup_cluster()
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 1445, in setup_cluster
    self.wait_for_cluster()
  File "<string>", line 2, in wait_for_cluster
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/utils.py", line 87, in wrap_f
    res = func(*arg, **kargs)
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 1237, in wait_for_cluster
    self.wait_for_active_spots()
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 1161, in wait_for_active_spots
    spots = spots or self.spot_requests
  File "/Users/oliviergrisel/coding/StarCluster/starcluster/cluster.py", line 722, in spot_requests
    filters = {'launch.group-id': self.cluster_group.id,
AttributeError: 'SecurityGroup' object has no attribute 'id'
```

**Comment by jtriley** [comment]
This is strange. If you don't mind, please double check your boto version with:

```
$ python -c 'import boto; print boto.__version__'
```

Also, there should be a crash report in $HOME/.starcluster/logs that would be useful to see.

I get the id with boto 2.5.2:

```
$ python -c 'import boto; print boto.__version__'
2.5.2
$ starcluster shell
[1]> print ec2.get_security_group('default').id
sg-a99174c2
```

**Comment by ogrisel** [comment]
Indeed:

```
$ python -c 'import boto; print boto.__version__'
2.0b3
```

Sorry for the noise I have something wrong on my system...

**Comment by jtriley** [comment]
@ogrisel No problem at all, thanks for double checking.

**Comment by ogrisel** [comment]
FYI, the culprit was [gsutil](https://developers.google.com/storage/docs/gsutil) which was coming  with its own embedded copy of boto polluting the python path of the other modules...

**Comment by jtriley** [comment]
@ogrisel Wow, that's ugly. They should either put the old version of boto within their namespace (e.g. gsutil.boto) or declare boto-2.0b3 in install_requires in setup.py (better approach IMO).

**Pull request closed without merging**
