### PR TITLE
Don't crash if the connection has an error

### PR DESCRIPTION
**Pull request by FinchPowers**
Fixes crahses associated to

```
File "/usr/local/lib/python2.7/dist-packages/paramiko-1.15.1-py2.7.egg/paramiko/transport.py", line 731, in     open_channel
    raise e
error: [Errno 104] Connection reset by peer


!!! ERROR - Oops! Looks like you've found a bug in StarCluster
!!! ERROR - Crash report written to: /home/datacratic/.starcluster/logs/crash-report-9893.txt
!!! ERROR - Please remove any sensitive data from the crash report
!!! ERROR - and submit it to starcluster@mit.edu
```

### CODE REVIEW

**Comment by jtriley** [comment]
Shouldn't we just catch the `Connection reset by peer` error instead of _all_ socket.errors? Otherwise we might be ignoring truly fatal errors and causing an endless loop waiting for instances to come up...

Also I think we should move the try/catch into the `is_ssh_up` method instead of `is_up`.

**Comment by FinchPowers** [comment]
Quickly searching the web, socket.error seems to be the exception associated to it. If we can do better okay.

For the second part I guess it depends how we see it. I would like StarCluster to never ever crash and handle all possible errors. I realize this is not the case in the core version, but mine will eventually terminate the bogus node.

On the other hand, if you want it to crash so that it can be handled by hand, then yeah, it should crash.

**Comment by jtriley** [comment]
After some more thought this might solve some fluky network issues for some users. The fact that you're logging this as a warning with exception info when it happens makes it easy for folks to make a decision if this keeps looping endlessly with the current code. 

I'm going to merge this with some very minor edits (mostly just moving try/except to `Node.is_ssh_up()`)

**Comment by justmytwospence** [comment]
I'm still getting this error when I launch clusters larger than ~80 nodes. Once I try to launch more than that, the marginal nodes throw this exception. Is this a network issue that is outside of StarCluter's hands?

**Comment by FinchPowers** [comment]
I don't think it's related to the size of the cluster.
Do you use spot instances? It can happen if the instance dies while it's being initialized.

**Comment by justmytwospence** [comment]
No I'm not using spot instances.

**Pull request merged**
