### PR TITLE
add efs plugin, with boto3 dependency

### PR DESCRIPTION
**Pull request by cariaso**
currently interferes with cluster termination, due to 

!!! ERROR - DependencyViolation: resource sg-1bbff57f has a dependent object
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 101, in execute
    self.terminate(cluster_name, force=self.opts.force)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 87, in terminate
    self._terminate_cluster(cl)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 64, in _terminate_cluster
    cl.terminate_cluster()
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1903, in terminate_cluster
    self.ec2.delete_group(sg)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/awsutils.py", line 268, in delete_group
    ret_val = group.delete()
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/ec2/securitygroup.py", line 89, in delete
    dry_run=dry_run
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/ec2/connection.py", line 3037, in delete_security_group
    return self.get_status('DeleteSecurityGroup', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>DependencyViolation</Code><Message>resource sg-1bbff57f has a dependent object</Message></Error></Errors><RequestID>59f183c5-ef60-4ddb-ac9a-a64d37d7a1c4</RequestID></Response>

but I expect to be able to resolve that after discussion with a developer more experienced in the starcluster codebase.

### CODE REVIEW

**Comment by cancan101** [comment]
Is there no way to use just the original boto here?

**Comment by cariaso** [comment]
correct. boto seems to be in 'no new features' mode, and efs is only in boto3.

**Comment by cariaso** [comment]
I've also noticed the on_shutdown() method for plugins, and am currently working on using that to release the security group.

**Comment by vasisht** [comment]
Is the security group still attached to the efs object when you're trying
to delete it? That may explain the dependency violation.

On Sunday, November 15, 2015, cariaso notifications@github.com wrote:

> I've also noticed the on_shutdown() method for plugins, and am currently
> working on using that to release the security group.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jtriley/StarCluster/pull/563#issuecomment-156890106.

## 

Pour trouver les limites du possible il faut tenter l'impossible.

**Comment by cariaso** [comment]
@vasisht yes. the reason is clear, even the solution is. What wasn't clear was where to put the fix. as my most recent comment indicates, I believe with on_shutdown() I've found my solution, and am working on an updated version now.

**Pull request closed without merging**
